{{- $root := . }}
{{- $fetchedcluster :=  (lookup "provisioning.cattle.io/v1" "Cluster" "fleet-default" .Values.cluster.name) }}
{{- if ($fetchedcluster.status| default nil).clusterName | default nil }}
  {{- range $index, $project := (lookup "management.cattle.io/v3" "Project"  $fetchedcluster.status.clusterName "").items }}
    {{- if hasKey $project.metadata.labels "authz.management.cattle.io/system-project" }}
      {{- if eq (index $project.metadata.labels "authz.management.cattle.io/system-project") "true" }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: neuvector-crd-{{ $.Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "neuvector-crd"
  repoName: "rancher-charts"
  releaseName: "neuvector-crd"
  version: 103.0.3+up2.7.6
  values:
    global:
      cattle:
        clusterId: {{ $fetchedcluster.status.clusterName }}
        clusterName: {{ $.Values.cluster.name }}
        rkePathPrefix: ''
        rkeWindowsPathPrefix: ''
        systemDefaultRegistry: ''
        systemProjectId: {{ $project.metadata.name }}
        url: {{ $.Values.cluster.url }}
  defaultNamespace: "cattle-neuvector-system"
  targets:
  - clusterName: {{ $.Values.cluster.name }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  

