# cluster specific values
cluster:
  # specify cluster name
  name: dbiservices-template-rke2-ec2

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false
  # specify fqdn of local access endpoint
  # fqdn: foo.bar.example
  # specify cacert of local access endpoint
  # caCerts: ""

